title: Vladimir Cazacu
description: ""
baseurl: ""
url: https://volod.xyz

theme: cvless

# site settings
taglong: Sr. Technical Artist with experience in film and video games.
tagshort: Vladimir Cazacu

# author settings
author:
  name: Vladimir Cazacu
  email: vladimir@volod.xyz
photo: assets/files/photo.jpg
address: Foobar Hall 1.23
phone: +1 234 567 890

# social media links
social:
  #facebook: username
  #github: username
  #instagram: username
  linkedin: volodXYZ
  #stackoverflow: 0000000/username
  x: volodXYZ

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
